name: Format

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to check formatting
        run: npm run prettier -- --check
        continue-on-error: false # Fail the workflow if formatting issues are found
