name: Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or whichever version your project requires

      - name: Install dependencies
        run: npm install

      - name: Run Prettier to check formatting
        run: npm run format -- --check

      - name: Run ESLint to check for linting issues
        run: npm run lint
